name: Run app.py daily

on:
  schedule:
    - cron: '1 0 * * *'  # Runs at 00:01 UTC every day
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify Python 3.10 or 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python app.py
      env:
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        REQUISITION_ID: ${{ secrets.REQUISITION_ID }}
        WHATSAPP_URL: ${{ secrets.WHATSAPP_URL }}
        NUMBER: ${{ secrets.NUMBER }}